apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  labels:
    app: php-app
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: kingakube/php-app:latest  # Update with your image name
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
